
variables:
  GIT_STRATEGY: fetch

stages:
  - lesson6


lesson6:
  stage: lesson6
  script:
    - ansible-playbook -v -i hosts -e "env_type=recipient" -e "way_type=$CI_PROJECT_DIR" lesson6.yml --ask-pass --ask-become-pass
  tags:
    - ansible.alamics.ru
  environment:
    name: recipient
  only:
    - branches
  when: manual
