
variables:
  GIT_STRATEGY: fetch

stages:
  - external_roles
  - lesson3



external_roles:
  stage: external_roles
  script:
    - ansible-playbook -v -i hosts -e "env_type=razif" -e "way_type=$CI_PROJECT_DIR" external_roles.yml --ask-pass --ask-become-pass
  tags:
    - ansible.alamics.ru
  environment:
    name: razif
  only:
    - branches
  when: manual

lesson3:
  stage: lesson3
  script:
    - ansible-playbook -vvv -i hosts -e "env_type=recipient" -e "way_type=$CI_PROJECT_DIR" lesson3.yml --ask-pass --ask-become-pass
  tags:
    - ansible.alamics.ru
  environment:
    name: recipient
  only:
    - branches
  when: manual
