variables:
  GIT_STRATEGY: fetch

stages:
  - lesson5


  
lesson5:
  stage: lesson5
  script:
    - ansible-playbook -vv -i hosts -e "env_type=recipient" -e "way_type=$CI_PROJECT_DIR" lesson5.yml --ask-pass --ask-become-pass
  tags:
    - ansible.alamics.ru
  environment:
    name: recipient
  only:
    - branches
  when: manual
