variables:
  GIT_STRATEGY: fetch

stages:
  - lesson2

lesson2:
  stage: lesson2
  script:
    - ansible-playbook -i hosts -e "env_type=recipient" -e "way_type=$CI_PROJECT_DIR" lesson2.yml --ask-pass --ask-become-pass
  tags:
    - ansible.alamics.ru
  environment:
    name: recipient
  only:
    - branches
  when: manual
