---

- name: create a user and give him rights
  user:
    name: "{{ item.login }}"
    password: "{{ item.pass }}"
    shell: /bin/bash
    groups: wheel
    state: present
    append: yes
    create_home: yes
  with_list: "{{ new_account }}"

- name: create a key for the user
  import_tasks: roles/key/tasks/main.yml
