---

- name: install epel-release
  yum:
    name:
      - epel-release
    state: latest

- name: install auxiliary packages
  yum:
    name:
      - mc
      - tar
      - unzip
      - python3
    state: latest
