---
- name: download mariadb_repo_setup
  get_url:
    url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    dest: /tmp/mariadb_repo_setup
    mode: 'a+x'

- name: turn on mariadb_repo
  command: /tmp/mariadb_repo_setup --mariadb-server-version="{{ mariadb_version }}"

- name: install mariadb
  yum:
    name:
      - MariaDB-server
      - MariaDB-client
      - MySQL-python
    state: latest

- name: turn on mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: set mysql root pass
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_host: "localhost"
    user: root
    host: "localhost"
    password: "{{ mariadb_root_new_password }}"

- name: remove anonymous users
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_new_password }}"
    user: ''
    host_all: yes
    state: absent

- name: remove test database
  mysql_db: 
    login_user: root
    login_password: "{{ mariadb_root_new_password }}"
    db: test
    state: absent

- name: remove test database priviledges
  block:
    - shell: mysql -u root -p{{ mariadb_root_new_password }} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    - shell: mysql -u root -p{{ mariadb_root_new_password }} -e "FLUSH PRIVILEGES"
