---
- name: download file
  get_url:
    url: https://raw.githubusercontent.com/ansible/ansible/devel/README.rst
    dest: "/tmp/{{ site_folder }}/README.rst"
    mode: 0775
    owner: ask1
    group: ask2
    