
ansible_user: ans
ansible_password: Qwe123
ansible_become_password: Qwe123
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

new_account: lesson3
new_account_password: "{{ 'Qaz@123' | password_hash('sha256', 'mysecretsalt') }}"

site_folder: lesson3

site_name: "192.168.57.128"



nginx_worker_processes: auto

nginx_port: 80

nginx_upstreams_name: myapp1
nginx_upstreams_strategy: "ip_hash"
